printWidth: 100
tabWidth: 4
singleQuote: true
semi: false
jsxSingleQuote: true
quoteProps: as-needed
trailingComma: none
bracketSpacing: true
bracketSameLine: true
plugins:
  - "prettier-plugin-tailwindcss"
  - "@ianvs/prettier-plugin-sort-imports"

importOrder:
  - "^react(.*)$"
  - ""
  - "<THIRD_PARTY_MODULES>"
  - ""
  - "^@/router[/]?(.*)$"
  - ""
  - "^@/assets[/]?(.*)$"
  - ""
  - "^@/shared[/]?(.*)$"
  - ""
  - "^\\.\\./(.*)$"
  - "^\\./(.*)$"
  - ""
  - "^[.]"
importOrderParserPlugins:
  - "typescript"
  - "jsx"
  - "decorators-legacy"
importOrderTypeScriptVersion: "5.2.2"
